language: node_js
node_js:
  - "0.11"
  - "0.10"

install: npm install
before_script:
  - gulp compile
  - gulp test

after_script: cat ./codecoverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./codecoverage